name: GitHub Checkout Action Demo
on: [push]
jobs:
  Explore-GitHub-Checkout-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          git describe --always --match "v*"
